<a href="https://colab.research.google.com/github/PMcTwist/Machine-Learning-Course/blob/main/Notebook1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Importing Libs **

In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

Initialize the dataset and define values

In [8]:
dataset = pd.read_csv('./sample_data/california_housing_test.csv')
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

Print out the data to the screen for funzies

In [9]:
print(X)

[[-122.05     37.37     27.     ... 1537.      606.        6.6085]
 [-118.3      34.26     43.     ...  809.      277.        3.599 ]
 [-117.81     33.78     27.     ... 1484.      495.        5.7934]
 ...
 [-119.7      36.3      10.     ...  693.      220.        2.2895]
 [-117.12     34.1      40.     ...   46.       14.        3.2708]
 [-119.63     34.42     42.     ...  753.      260.        8.5608]]


In [10]:
print(Y)

[344700. 176500. 270500. ...  62000. 162500. 500001.]
